Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ForeignKey.Models
{
    public class AppDbContext: DbContext
    {
        public AppDbContext( DbContextOptions options ):base(options)
        {
            
        }

        public DbSet <Student> Students{ get; set; }
        public DbSet <Course> Courses{ get; set; }
        public DbSet <Routine> Routines{ get; set; }
    }
}

Models/Course.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ForeignKey.Models
{
    public class Course
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace ForeignKey.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Routine.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ForeignKey.Models
{
    public class Routine
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Time { get; set; }
        public string CourseId { get; set; }
        
    }
}

Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ForeignKey.Models
{
    public class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CourseId { get; set; }
        public Course Course { get; set; }
    }
}

Models/StudentCreateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ForeignKey.Models
{
    public class StudentCreateViewModel
    {
        public IEnumerable<Course> courses { get; set; }
        public Student student { get; set; }
        public int CourseId { get; set; }
        public string StudentName { get; set; }
    }
}

Controllers/CourseController.cs
using ForeignKey.Models;
using ForeignKey.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ForeignKey.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseService _courseService;

        public CourseController(ICourseService courseService)
        {
            _courseService = courseService;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _courseService.GetCourses();
            return View(data);
        }

        public async Task<IActionResult> Details(int id)
        {
            var data = await _courseService.GetCourse(id);
            return View(data);
        }
        public IActionResult Delete(int id)
        {
            _courseService.DeleteCourse(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Create(int id)
        {
            var course = new Course();
            if(id > 0)
            {
                course = await _courseService.GetCourse(id);
            }
            return View(course);
        }
        [HttpPost]
        public async Task<IActionResult> Create( Course course)
        {
            if (ModelState.IsValid)
            {
               await _courseService.AddCourse( course);
            }
            return RedirectToAction(nameof(Index));

        }
    }
}

Controllers/HomeController.cs
using ForeignKey.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ForeignKey.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RoutineController.cs
using ForeignKey.Models;
using ForeignKey.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ForeignKey.Controllers
{
    public class RoutineController : Controller
    {
        private IRoutineService  _routineService;
        public RoutineController(IRoutineService routineService)
        {
            _routineService = routineService;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _routineService.GetRoutines();
            return View(data);
        }
        public async Task<IActionResult> Details(int id)
        {
            var data = await _routineService.GetRoutine(id);
            return View(data);
        }

        public IActionResult Delete(int id)
        {
            _routineService.DeleteRoutine(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Create(int id=0)
        {
            Routine routine = new Routine();

            if (id != 0)
            {
                routine = await _routineService.GetRoutine(id);
            }
            return View(routine);
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(Routine routine)
        {
            if (ModelState.IsValid)
            {
                await _routineService.AddRoutine(routine);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/StudentController.cs
using ForeignKey.Models;
using ForeignKey.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ForeignKey.Controllers
{
    public class StudentController : Controller
    {
        private IStudentService _studentService;
        private readonly ICourseService _courseService;

        public StudentController(IStudentService studentService, ICourseService courseService)
        {
            _studentService = studentService;
            _courseService = courseService;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _studentService.GetStudents();
            return View(data);
        }
        public async Task<IActionResult> Details(int id)
        {
            var data = await _studentService.GetStudent(id);
            return View(data);
        }

        public IActionResult Delete(int id)
        {
            _studentService.DeleteStudent(id);
           return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Create(int id)
        {
            Student student = new Student();

            if( id > 0)
            {
                student = await _studentService.GetStudent(id);
            }

            var result = new StudentCreateViewModel
            {
                student = student,
                courses = await _courseService.GetCourses(),
            };

            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Create(StudentCreateViewModel student)
        {
            if (ModelState.IsValid)
            {
                var student1 = new Student
                {
                    Id = 0,
                    Name = student.StudentName,
                    CourseId = student.CourseId
                };
              await _studentService.AddStudent(student1);
            }
            return RedirectToAction(nameof(Index));
        }
    }   
}

Views/Course/Create.cshtml
@model ForeignKey.Models.Course

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" value="@Model.Name"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control"  value="@Model.Code"/>
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <input type="hidden" value="@Model.Id" name="Id" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Course/Details.cshtml
@model ForeignKey.Models.Course

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Course/Index.cshtml
@model IEnumerable<ForeignKey.Models.Course>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>
    function confirmDelete(uniqueId, isDeleteClicked) {
        var deleteSpan = 'deleteSpan_' + uniqueId;
        var confirmDeleteSpan = 'confirmDeleteSpan_' + uniqueId;

        if (isDeleteClicked) {
            $('#' + deleteSpan).hide();
            $('#' + confirmDeleteSpan).show();
        } else {
            $('#' + deleteSpan).show();
            $('#' + confirmDeleteSpan).hide();
        }
    }

    function Validate(ctl, event) {
        event.preventDefault();
        swal({
            title: "Good job!",
            text: "You clicked the button!",
            icon: "success",
            button: "Aww yiss!",
        });
    }
</script>

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                <a class="btn btn-secondary" asp-controller="Course" asp-action="Details" asp-route-id="@item.Id">Details</a>

                <a class="btn btn-success" asp-controller="Course" asp-action="Create" asp-route-id="@item.Id">Update</a>

                <span  >


                    <span id="confirmDeleteSpan_@item.Id" style="display:none">
                        <span>Are you sure you want to delete?</span>
                        <a class="btn btn-danger" asp-controller="Course" asp-action="Delete" asp-route-id="@item.Id">Yes</a>
                        <a href="#" class="btn btn-primary"
                           onclick="confirmDelete('@item.Id', false)">No</a>
                    </span>

                    <span id="deleteSpan_@item.Id">
                        <a href="#" class="btn btn-danger"
                           onclick="confirmDelete('@item.Id', true)">Delete</a>
                    </span>
                </span>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Routine/Create.cshtml
@model ForeignKey.Models.Routine

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Routine</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" value="@Model.Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Time" class="control-label"></label>
                <input asp-for="Time" class="form-control" value="@Model.Time" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <input asp-for="CourseId" class="form-control" value="@Model.CourseId" />
                <span asp-validation-for="CourseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <input type="hidden" value="@Model.Id" name="Id" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Routine/Details.cshtml
@model ForeignKey.Models.Routine

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Routine</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Time)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CourseId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CourseId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Routine/Index.cshtml
@model IEnumerable<ForeignKey.Models.Routine>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<script>
    function confirmDelete(uniqueId, isDeleteClicked) {
        var deleteSpan = 'deleteSpan_' + uniqueId;
        var confirmDeleteSpan = 'confirmDeleteSpan_' + uniqueId;

        if (isDeleteClicked) {
            $('#' + deleteSpan).hide();
            $('#' + confirmDeleteSpan).show();
        } else {
            $('#' + deleteSpan).show();
            $('#' + confirmDeleteSpan).hide();
        }
    }
</script>


<h1>Index</h1>

<p>
    <a asp-action="Create" >Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Time)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CourseId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody id="111">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Time)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseId)
                </td>
               
                <td>

                    <a class="btn btn-secondary" asp-controller="Routine" asp-action="Details" asp-route-id="@item.Id">Details</a>

                    <a class="btn btn-success" asp-controller="Routine" asp-action="Create" asp-route-id="@item.Id">Update</a>

                    <span>


                        <span id="confirmDeleteSpan_@item.Id" style="display:none">
                            <span>Are you sure you want to delete?</span>
                            <a class="btn btn-danger" asp-controller="Routine" asp-action="Delete" asp-route-id="@item.Id">Yes</a>
                            <a href="#" class="btn btn-primary"
                               onclick="confirmDelete('@item.Id', false)">No</a>
                        </span>

                        <span id="deleteSpan_@item.Id">
                            <a href="#" class="btn btn-danger"
                               onclick="confirmDelete('@item.Id', true)">Delete</a>
                        </span>
                    </span>

                </td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ForeignKey</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ForeignKey</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Routine" asp-action="Index">Routines</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ForeignKey - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Student/Create.cshtml
@model ForeignKey.Models.StudentCreateViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="@Model.student.Name" class="control-label"></label>
                <input asp-for="@Model.student.Name" name="StudentName" class="form-control" value="@Model.student.Name" />
                <span asp-validation-for="@Model.student.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.student.CourseId" class="control-label"></label>
                <select asp-for="@Model.student.CourseId" name="CourseId" class="form-control" asp-items="ViewBag.CourseId">
                    @foreach (var item in Model.courses)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <input type="hidden" value="@Model.student.Id" name="Id" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Student/Details.cshtml
@model ForeignKey.Models.Student

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Student/Index.cshtml
@model IEnumerable<ForeignKey.Models.Student>

    @{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    }

<script>
    function confirmDelete(uniqueId, isDeleteClicked) {
        var deleteSpan = 'deleteSpan_' + uniqueId;
        var confirmDeleteSpan = 'confirmDeleteSpan_' + uniqueId;

        if (isDeleteClicked) {
            $('#' + deleteSpan).hide();
            $('#' + confirmDeleteSpan).show();
        } else {
            $('#' + deleteSpan).show();
            $('#' + confirmDeleteSpan).hide();
        }
    }
</script>
   

    <h1>Index</h1>

    <p>
        <a asp-action="Create" id="111">Create</a>
    </p>

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Course.Name)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
               
                <td>
                    @Html.DisplayFor(modelItem => item.Course.Name)
                </td>
                <td>
                    <a class="btn btn-secondary" asp-controller="Student" asp-action="Details" asp-route-id="@item.Id">Details</a>

                    <a class="btn btn-success" asp-controller="Student" asp-action="Create" asp-route-id="@item.Id">Update</a>

                    <span>


                        <span id="confirmDeleteSpan_@item.Id" style="display:none">
                            <span>Are you sure you want to delete?</span>
                            <a class="btn btn-danger" asp-controller="Student" asp-action="Delete" asp-route-id="@item.Id">Yes</a>
                            <a href="#" class="btn btn-primary"
                               onclick="confirmDelete('@item.Id', false)">No</a>
                        </span>

                        <span id="deleteSpan_@item.Id">
                            <a href="#" class="btn btn-danger"
                               onclick="confirmDelete('@item.Id', true)">Delete</a>
                        </span>
                    </span>
                </td>

            </tr>
}
        </tbody>
    </table>